#!/usr/bin/env bash
#write a bash script that install Nginx server

#update the sysytem
sudo apt update

#install nginx server
sudo apt install nginx

#server configurations
echo "Hello World!" > /var/www/html/index.html

sudo service nginx reload
sudo service nginx  start
