#!/usr/bin/env bash
#write a bash script that install Nginx server

#update the sysytem
sudo apt update

#install nginx server
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
#server configurations
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -n '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default
sudo service nginx  restart
