#!/usr/bin/env bash
#write a bash script that install Nginx server

#update the sysytem
sudo apt update

#install nginx server
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
#server configurations
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/luischaparroc permanent;/" /etc/nginx/sites-available/default
sudo service nginx  restart
