#!/usr/bin/env bash
#Double the number of webservers

#installing nginx
sudo apt update
sudo apt install nginx

server_name=$(hostname)

#adding custom header
sudo sed -i "/server_name_;/a\
	add_header X-Served-By $server_name;" /etc/nginx/sites-enabled/default
sudo service nginx restart
