#!/usr/bin/env bash
#Double the number of webservers

#installing nginx
sudo apt update
sudo apt install nginx

#adding custom header
sudo sed -i "/server_name_;/a\ add_header X-Served-By "$HOSTNAME";" /etc/nginx/sites-available/default
sudo service nginx restart
