#!/usr/bin/env bash
#Double the number of webservers

#installing nginx
sudo apt update
sudo apt install nginx

#adding custom header
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
