#!/usr/bin/env bash
#Install your load balancer

#install HAproxy
sudo apt -y update
sudo apt -y upgrade
#sudo apt-get install --no-install-recommends software-properties-common
#sudo add-apt-repository ppa:vbernat/haproxy-2.9

sudo apt-get -y install haproxy

balancer=\
"
frontend haproxy_balancer
	bind *:80
	mode http
	default_backend webserver

backend webserver
	balance roundrobin
	server 420083-web-01 52.1.28.34:80 check
	server 420083-web-02 34.224.5.156:80 check
"

#sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
