#!/usr/bin/env bash
#Install your load balancer

#install HAproxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9

sudo apt-get install haproxy=2.9.\*
